spring:
  datasource:
    password: Tulika@113311
    url: jdbc:postgresql://localhost:5432/rajupal
    username: rajupal
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
    path: /graphql
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 60000
    cache-names: stocks